### ISSUE TITLE
The `poetry poly check --strict` command does not seem to handle private packages from private repos

### ISSUE THREAD

**Issue by hstravis** [DavidVujic/python-polylith#247] opened 2024-08-11 01:22 UTC
The `poetry poly check --strict` command does not work with private packages installed from our team's private repo.

We are trying to use the poly check command in CI/CD jobs to detect dependency problems. The `--strict` arg helps detect dependency problems; however, it is not useful for our projects if it doesn't support private packages installed from our private repo.

**To Reproduce**
1. Open a terminal window 
2. Go to root of the project **which depends on packages from a private repo**
4. Run the command: `poetry poly check --strict`
5. See error

**Error Log**
Unfortunately, I cannot share the logs directly for...reasons. Here's a description of what they look like:

The `poetry poly check --strict` command complains about imports from our team's packages. For example, if the package is name `acme.magic-analysis` and the import statement is: `from magic_analysis import do_magic` then the `check` command will output something like:

`🤔 Cannot locate do_magic in magic_image`

**Expected behavior**
Both commands should succeed when project dependencies are correct.

**Screenshots**
*sorry*

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version: 3.11.7
 - Poetry version: 1.8.3
 - Polylith plugin version: 1.27.1

**Additional context**

Adding aliases fixes the `libs` command but not the `check` command. We're using a script like this:

```bash
#!/bin/bash
# Polylith utils used by developers and CI/CD jobs.

function getPolylithAliases {
    # Aliases are used to work around issues that the the polylith 
    # plugin has with some hal packages.
    echo "--alias acme-hal-numpy=hal_numpy"
    echo "--alias acme-mr-vectors=de_vectors"
    echo "--alias acme-hal-analyses=hal_analyses"
    echo "--alias acme-hal-analyses-juan=hal_analyses_juan"
    echo "--alias acme-hal-core=hal_core"
    echo "--alias acme-hal-flask-auth=hal_flask_auth"
    echo "--alias acme-hal-json=hal_json"
    echo "--alias acme-hal-reports=hal_reports"
    echo "--alias acme-hal-settings=hal_settings"
    echo "--alias acme-hal-plumbus-reports=hal_plumbus_reports"
    echo "--alias acme-hal-time=hal_time"
    echo "--alias acme-file-service-manager=file_service_manager"
    echo "--alias acme-flask-mr-logging=flask_mr_logging"
    echo "--alias acme-flask-file-service=flask_file_service"
    echo "--alias acme-flask-health-check=flask_health_extension"
    echo "--alias acme-juan-client=juan_client"
    echo "--alias acme-results-client=results_client"
    echo "--alias acme-monk-client=monk_client"
    echo "--alias acme-monk-core=monk_core"
    echo "--alias acme-monk-schemas=monk_schemas"
    echo "--alias acme-monk-plumbus=monk_plumbus"
    echo "--alias acme-monk-plumbus-transformer=monk_plumbus_transformer"
    }

function poly_check {
    # Compare dependencies between all projects in repo.
    # Ensure that all projects are using the same package versions.
    # Display any discrepancies. Non-zero return if any discrepancies.
    poetry poly check --strict \
        $(getPolylithAliases) \
        || return $?
}

function poly_libs {
    # Display dependencies between all projects in repo.
    # Highlight any discrepancies.
    poetry poly libs --strict \
        $(getPolylithAliases) \
        || return $?
}```

**Comment by DavidVujic** [comment] 2024-08-11 07:13
Thank you for the detailed description @hstravis!

Polylith shouldn't do anything different with packages from private repos, but I will look into it! Could it be the structure of the packages? Are the packages named with the `acme.` prefix, but doesn't contain a top namespace in the package itself? Can you share something from the lock-file about one of those packages?

I think the prefix could be the reason, and a scenario that I haven't seen before.

**Comment by DavidVujic** [comment] 2024-08-11 09:53
I realize that the package seems to be located, but not the import from it 🤔 

> 🤔 Cannot locate do_magic in magic_image

Can you share some info about the structure in the package(s)?

How are they added into the virtual environment? Are all within a top folder `acme` with subfolders containing the code?

**Comment by hstravis** [comment] 2024-08-11 13:34
> Thank you for the detailed description @hstravis!
> 
> Polylith shouldn't do anything different with packages from private repos, but I will look into it! Could it be the structure of the packages? Are the packages named with the `acme.` prefix, but doesn't contain a top namespace in the package itself? Can you share something from the lock-file about one of those packages?
> 
> I think the prefix could be the reason, and a scenario that I haven't seen before.

Here's an obfuscated excerpt from the lock file:

```toml
[[package]]
name = "acme-hal-analyses"
version = "4.1.0.1251"
description = "Common functions useful for analysis packages"
optional = false
python-versions = "*"
files = [
    {file = "acme.hal_analysis_utils-2.3.0.1251-py3-none-any.whl", hash = "sha256:d7393b79384af1fc7e752086fcea34a762eb9498ccffd5029ee883b97eb03ff2"},
    {file = "acme_hal_analysis_utils-2.3.0.1251.tar.gz", hash = "sha256:6231f42c502684a89412dbd3f39f3f12a986446d35e0e88cff8b4dd1287048b5"},
]
```

**Comment by hstravis** [comment] 2024-08-11 13:44
> I realize that the package seems to be located, but not the import from it 🤔
> 
> > 🤔 Cannot locate do_magic in magic_image
> 
> Can you share some info about the structure in the package(s)?
> 
> How are they added into the virtual environment? Are all within a top folder `acme` with subfolders containing the code?

There is no `acme` top namespace.

If the package name is `acme.hal_analysis_utils` then the top namespace is: `hal_analysis_utils`

Most `acme` packages follow the same pattern. But not all of them. For example: the top namespace for `acme.file_service_manager` is `hal_files.

**Comment by DavidVujic** [comment] 2024-08-11 14:17
Thank you!

The import that isn't found (even if the top-namespace is): how does the package folder/file structure look like in the `.venv`?

**Comment by hstravis** [comment] 2024-08-11 14:28
> Thank you!
> 
> The import that isn't found (even if the top-namespace is): how does the package folder/file structure look like in the `.venv`?

I *think* these are the relevant parts of the `site-packages` folder in the virtual environment:

```
site-packages/
  hal_analysis_utils/
    # contains source code
  acme.hal_analysis_utils-4.1.0.1251.dist-info/
    INSTALLER
    METADATA
    RECORD
    top_level.txt
    WHEEL
```

Where `top_level.txt` contains: 

```text
hal_analysis_utils
```

And `METADATA` contains:

```text
Metadata-Version: 2.1
Name: acme.hal-analysis-utils
Version: 4.1.0.1251
Summary: Common functions useful for analysis packages
Author-email: HAL Team <hal_team@acme.com>
Project-URL: Repository, https://github.com/acme/applications.analytics.hal.analysis-utils
Classifier: Programming Language :: Python :: 3
Requires-Dist: numpy
Requires-Dist: acme.hal-apm
Requires-Dist: acme.hal-core >=1.1.1
Requires-Dist: acme.hal-numpy >=1.1.0.13
Requires-Dist: pareto ~=1.1
Requires-Dist: imageio >=2.0
Requires-Dist: dacite >=1.6.0
```

**Comment by DavidVujic** [comment] 2024-08-11 14:41
This should be picked up by the Polylih tool. You shouldn't need to use the `--alias` option either. This is probably a bug, and I will try to replicate it. What is the result if you run the poly commands without the alias?

**Comment by DavidVujic** [comment] 2024-08-11 14:44
Also: the tool does lookups in the project-specific lock files. Just to double check, are they updated?

**Comment by hstravis** [comment] 2024-08-11 14:56
Oh that would be embarrassing. Checking.

**Comment by hstravis** [comment] 2024-08-11 15:02
> The tool does lookups in the project-specific lock files. Just to double check, are they updated?

Confirmed that all lock files are updated.

**Comment by hstravis** [comment] 2024-08-11 15:05
> This should be picked up by the Polylih tool. You shouldn't need to use the `--alias` option either. This is probably a bug, and I will try to replicate it. What is the result if you run the poly commands without the alias?

It doesn't just complain about not being able to find imports. It also complains about not being able to find packages. Going back to the original example:

```text
🤔 Cannot locate do_magic in magic_image
🤔 Cannot locate magic_analysis in magic_image
```

Where `do_magic` is a function imported from the `magic_analysis` package.

**Comment by hstravis** [comment] 2024-08-11 15:09
BTW - The `libs` command also complains about not finding packages when aliases are not specified.

**Comment by DavidVujic** [comment] 2024-08-11 15:18
Thank you @hstravis - I'll work on this issue. The commands should work without any aliases, and also with the `--strict` option.

**Comment by DavidVujic** [comment] 2024-08-11 16:04
I think I have found a possible cause, and that is when the tool picks top namespaces from third-party libraries. From your example, it looks like a package can have different names (the name added in the pyproject.toml, the environment dist folder and the defined "name" in the metadata:

acme-hal-analyses
acme.hal_analyses
acme_hal_analyses

The solution that I will give a try is to normalize the names: replace hyphens and dots with underscore.

I will do some testing and experimenting and add a note here when there's a new version available!

**Comment by DavidVujic** [comment] 2024-08-11 18:49
I have released 1.27.2 of the Poetry plugin, that will normalize the third-party library names. Please let me know if that solves it. I'll keep this issue open.

My hopes are that it will solve the issues with `--strict` and that you won't need the `--alias` option either. 🙏 😄

**Comment by hstravis** [comment] 2024-08-11 19:58
> I have released 1.27.2 of the Poetry plugin, that will normalize the third-party library names. Please let me know if that solves it. I'll keep this issue open.
> 
> My hopes are that it will solve the issues with `--strict` and that you won't need the `--alias` option either. 🙏 😄

The `--alias` args are no longer required but `poetry poly check --strict` still complains about not finding imports. It is the same message as I was seeing previously when I specified aliases. So it seems to find packages but not the things imported from those packages. So it's significantly better but not truly fixed.

`poetry poly libs --strict` behaves as expected now - no need to specify aliases. That makes things easier to maintain.

**Comment by DavidVujic** [comment] 2024-08-14 09:31
I am trying to reproduce the error, but fail. 😞 

This is how I have tried to simulate it:

Adding this to my test-repo `.venv`:
```
.venv/lib/python3.12/site-packages/hal_analysis_utils/__init__.py
.venv/lib/python3.12/site-packages/acme.hal_analysis_utils-4.1.0.1251.dist-info/INSTALLER
.venv/lib/python3.12/site-packages/acme.hal_analysis_utils-4.1.0.1251.dist-info/METADATA
.venv/lib/python3.12/site-packages/acme.hal_analysis_utils-4.1.0.1251.dist-info/RECORD
.venv/lib/python3.12/site-packages/acme.hal_analysis_utils-4.1.0.1251.dist-info/WHEEL
.venv/lib/python3.12/site-packages/acme.hal_analysis_utils-4.1.0.1251.dist-info/top_level.txt
```
(I also added contents to the files above)

Then I added this import in one component:
```python
from hal_analysis_utils import helloworld

# the __init__.py I added in the .venv has one function "helloworld"
print(helloworld())
```
The `poly check` would report a missing dependency (correctly).

Then I added the dependency to the project using this code:
```toml
[tool.poetry.dependencies]
acme-hal-analysis-utils = "*"
```
The Polylith tool looks into the lock-files too, so I added this to the project lock-file:

```toml
[[package]]
name = "acme-hal-analysis-utils"
version = "4.1.0.1251"
description = "Common functions useful for analysis packages"
optional = false
python-versions = "*"
files = [
    {file = "acme.hal_analysis_utils-4.1.0.1251-py3-none-any.whl", hash = "sha256:d7393b79384af1fc7e752086fcea34a762eb9498ccffd5029ee883b97eb03ff2"},
    {file = "acme_hal_analysis_utils-4.1.0.1251.tar.gz", hash = "sha256:6231f42c502684a89412dbd3f39f3f12a986446d35e0e88cff8b4dd1287048b5"},
]
```

The `poly check --strict` does not report anything when having this setup.

Then I experimented with changing the things in the lockfile: from `acme` to `z_acme` in the name and the "files", and the `poly check --strict` command reported a missing dependency, that I belive is correct.

Is there something that I have missed or named wrong in my example?

**Comment by hstravis** [comment] 2024-08-14 13:26
> Is there something that I have missed or named wrong in my example?

Wow, thanks for your efforts! Everything makes sense to me and it matches pretty closely to what I see on my end. One difference that _shouldn't_ matter: Instead of defining `helloworld()` in `__init__.py`, create `helloworld.py` with a `HelloWorld()` class in it then import like: 

```python
from hal_analysis_utils.helloworld import HelloWorld
```

That more closely mimics the situation on my end.

**Comment by hstravis** [comment] 2024-08-14 13:27
Also, I'm using python 3.11.7. Actually, I'll try it with 3.12 and see if that makes any difference.

**Comment by hstravis** [comment] 2024-08-14 13:50
> Also, I'm using python 3.11.7. Actually, I'll try it with 3.12 and see if that makes any difference.

This is more difficult than I expected because the project is using a version of scipy that requires python <3.12. It's too difficult to untangle things. Sorry.

**Comment by DavidVujic** [comment] 2024-08-14 13:53
I'll try that! And I'll change it to run with Python 3.11.

**Comment by DavidVujic** [comment] 2024-08-14 14:12
Here's a recording of the results (scaled down and speeded up for less size).

I think it behaves as expected, with the example setup that I have done. The `poly libs` command reports on missing dependencies in development, because I didn't add it there (the root `pyproject.toml`).

(I also modified the root lock-file and project file to make sure all reports of missing deps were solved.)

Do you have any ideas, maybe I have created a "happy path" example here? 😄 

![poly-check-acme](https://github.com/user-attachments/assets/e28d502b-7d69-4054-81b4-8c759749cbb9)

**Comment by DavidVujic** [comment] 2024-08-14 14:28
Does the name in the `pyproject.toml` look right?


`acme-hal-analysis-utils = "*"`

**Comment by hstravis** [comment] 2024-08-14 14:44
> Does the name in the `pyproject.toml` look right?
> 
> `acme-hal-analysis-utils = "*"`

Yes. It shouldn't matter but a `~` version is _always_ specified: `acme-hal-analysis-utils = ">=2.3,<3.0"`

**Comment by DavidVujic** [comment] 2024-08-14 14:55
Could you share some more variations of the `top_level.txt` files for the libraries? I'm suspecting that I have made some assumptions about the content in those files.

**Comment by DavidVujic** [comment] 2024-08-18 10:55
About the imported function that isn't recognized when running `poetry poly check --strict` - would it be possible for you to share this info? I cannot reproduce it with my local testing.

I would very much appreciate to know how:
- that particular library is added in the `pyproject.toml`
- the function is imported in the python module
- the contents of `poetry.lock` file for that library
- the `.venv`: the dist-info and the top folder with the python code for that particular library

As an alternative, I'm open for a Zoom session where you could share your screen maybe?

**Comment by DavidVujic** [comment] 2024-08-28 09:19
I don't think it has to do with private repositories. I have tried with adding a library in a private PyPI repo and the `poly check --strict` command returns with a success exit code without any errors.

I will close this, please reopen or create a new issue if this still is an issue 🙏

**Closed by DavidVujic** 2024-08-28 09:19 UTC
