### ISSUE TITLE
test folder not being created after workspace creationg - issue with 

### ISSUE THREAD

**Issue by ljubisa-dobric** [DavidVujic/python-polylith#281] opened 2024-10-29 07:55 UTC
**Describe the bug**

**To Reproduce**
1. Open a terminal window 
2. Go to root of the project
4. Run the command 'uv run poly create workspace --name test_project --theme loose'
5. See error

**Error Log**
If applicable, add the error logs.

**Expected behavior**
When creating new workspace folder structure is not as described in documentation. Test folder is not created properly. 
Also when creating components with command uv run poly create component --name my_example_component, it creates component with workspace folder below first then component , this is little bit different then video and sample repo.
 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version:  Python 3.12
 - Poetry version: uv (latest)

**Additional context**

**Comment by DavidVujic** [comment] 2024-10-29 08:05
Thank you for reporting!

What is the error that you get?

I noticed that the latest uv doesn’t add the hatchling backend by default, could that be the issue? Yesterday, I updated the docs about this: https://davidvujic.github.io/python-polylith-docs/setup/#edit-the-configuration_1

**Comment by DavidVujic** [comment] 2024-10-29 08:55
@ljubisa-dobric The `test` folder (if not already existing) should be created when you add a new component or base. I tried by creating a new repo and ran the poly commands to create a new workspace and components successfully. I cannot reproduce any error. Can you share what might have failed?

My guess is that the root pyproject.toml didn't contain the `hatchling` build backend as described in the docs (see link in post above). I will look into that if I can simplify this for `uv` users, to not require that part at the root project file. But currently you will need to add this to make it work smoothly with the Polylith tool:
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```
and
```toml
[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]
```

**Comment by DavidVujic** [comment] 2024-10-31 07:20
Closing this, please reopen if you still have this issue.

**Closed by DavidVujic** 2024-10-31 07:20 UTC
